### ISSUE TITLE
Will this be open sourced?

### ISSUE THREAD

**Issue by blakek** [SingletonIT/MUNO-release#1]
I was curious if this will be open sourced.  If it is, there are a few things I'd like to help out with.  If not, that's fine, too.

Thanks for this project!

**Comment by glenndeb** [comment]
I am thinking about it. But I have some security concerns.  Do you got any experience in open sourcing a project?

**Comment by deadcoder0904** [comment]
@glenndeb Just make sure you aren't committing any of your API keys. Like I consider my simplest open source app (https://github.com/deadcoder0904/serverless-hello-world) which needs secret API keys so I included all of it in a `env.example.json` file & I added my file `env.json` to `.gitignore`

So in short, put your secret keys in `env.json` like 

# env.json

```json
{
  "API_KEY": "SUPER_SECRET_DONT_TELL_ANYONE"
}
```

Make a duplicate `env.example.json` for other people to know where their API keys should go like

```json
{
  "API_KEY": "<YOUR_API_KEY>"
}
```

Add `env.json` to `.gitignore`

# .gitignore

```gitignore
env.json
```

Also, interested in your app if it does go open source route :)

There are some issues like Icons are opposite for Sound on YouTube Player & some feature requests like FullScreen Video Player. Hopefully Open Source might help fix that. Love your app. Its really amazing. Tried it for the first time & absolutely love the UI & Concept :)

**Comment by glenndeb** [comment]
Thanks for the information / help @deadcoder0904 @blakek  i'm going to open source Muno in the next couple of weeks. I hope you will contribute to the open sourced Muno!

**Comment by glenndeb** [comment]
@deadcoder0904 @blakek  Muno is open-sources and the first version with limited documentation is published in my private Github account https://github.com/glenndeb/MUNO. Please ask me anything if you need help

**Comment by deadcoder0904** [comment]
Thank you @glenndeb ❤️

**Comment by blakek** [comment]
@glenndeb Thanks, this is awesome!
